# Generated by Django 2.0.5 on 2018-08-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntcadventures', '0002_auto_20180819_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
