# Generated by Django 2.0.5 on 2018-08-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntcadventures', '0004_auto_20180819_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='entry_media')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntcadventures.Entry')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
